baseURL = 'https://hacklabucm.github.io/'
languageCode = 'en-us'
title = 'Hacklab UCM'
theme = 'hugo-book'
[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true
